apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoomsig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoomsig
  template:
    metadata:
      labels:
        app: zoomsig
    spec:
      containers:
      - image: gcr.io/webapp-prod-96269/zoomsig:1.0
        name: zoomsig
        ports:
        - containerPort: 4000
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 45Mi
          requests:
            cpu: 150m
            memory: 30Mi
apiVersion: v1
kind: Service
metadata:
  name: zoomsig
  labels:
    run: zoomsig
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: zoomsig
  selector:
    app: zoomsig
